/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zanr;
import domain.Zanr;
/**
 *
 * @author Korisnik
 */
public class ZanrForma extends javax.swing.JDialog {
    Zanr zanr;

    /**
     * Creates new form ZanrForma
     */
    public ZanrForma(java.awt.Frame parent, boolean modal, Zanr zanr) {
        super(parent, modal);
        initComponents();
        this.zanr = zanr;
        lblZanrID.setText("ZanrID: " + zanr.getZanrID());
        lblNaziv.setText("Naziv zanra: " + zanr.getNaziv());
        setLocationRelativeTo(null);
        setTitle("Zanr - " + zanr.getNaziv());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZanrID = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblZanrID.setText("ZanrID:");

        lblNaziv.setText("Naziv zanra: ");

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZanrID)
                            .addComponent(lblNaziv)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIzadji)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnIzadji)
                .addGap(18, 18, 18)
                .addComponent(lblZanrID)
                .addGap(48, 48, 48)
                .addComponent(lblNaziv)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblZanrID;
    // End of variables declaration//GEN-END:variables
}
