/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import controller.ClientController;
import domain.Bibliotekar;
import domain.Clan;
import domain.Knjiga;
import forme.clan.ClanForma;
import forme.clan.DodajClana;
import forme.knjiga.DodajKnjiguForma;
import forme.knjiga.KnjigaForma;
import forme.knjiga.OcenaKnjige;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli.ModelTabeleClanovi;
import modeli.ModelTabeleKnjige;
import session.Session;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {
    Bibliotekar ulogovani;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani bibliotekar: " + ulogovani.getIme() + " " + ulogovani.getPrezime());
        ModelTabeleClanovi model = new ModelTabeleClanovi();
        Thread thread = new Thread(model);
        thread.start();
        tblClanovi.setModel(model);
        ModelTabeleKnjige modelKnjige = new ModelTabeleKnjige();
        Thread thread1 = new Thread(modelKnjige);
        thread1.start();
        tblKnjige.setModel(modelKnjige);
        setTitle("Main - " + ulogovani.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDodajClana = new javax.swing.JButton();
        btnPrikaziClana = new javax.swing.JButton();
        txtPretragaČlanova = new javax.swing.JTextField();
        btnObrisiClana = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnDodajKnjigu = new javax.swing.JButton();
        btnPrikaziKnjigu = new javax.swing.JButton();
        txtPretragaKnjiga = new javax.swing.JTextField();
        btnOceniKnjigu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblUlogovani.setText("Ulogovani bibliotekar:");

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClanovi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pretraga članova:");

        btnDodajClana.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDodajClana.setText("Dodaj novog člana");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        btnPrikaziClana.setText("Prikazi selektovanog clana");
        btnPrikaziClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziClanaActionPerformed(evt);
            }
        });

        txtPretragaČlanova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaČlanovaKeyReleased(evt);
            }
        });

        btnObrisiClana.setText("Obrisi clana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblKnjige);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pretraga knjiga:");

        btnDodajKnjigu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDodajKnjigu.setText("Dodaj novu knjigu");
        btnDodajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajKnjiguActionPerformed(evt);
            }
        });

        btnPrikaziKnjigu.setText("Prikazi selektovanu knjigu");
        btnPrikaziKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziKnjiguActionPerformed(evt);
            }
        });

        txtPretragaKnjiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKnjigaKeyReleased(evt);
            }
        });

        btnOceniKnjigu.setText("Oceni knjigu");
        btnOceniKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOceniKnjiguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnPrikaziClana, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblUlogovani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPretragaKnjiga))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPretragaČlanova))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnDodajKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnOceniKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnPrikaziKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblUlogovani)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretragaČlanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajClana)
                    .addComponent(btnPrikaziClana)
                    .addComponent(btnObrisiClana))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPretragaKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajKnjigu)
                    .addComponent(btnPrikaziKnjigu)
                    .addComponent(btnOceniKnjigu))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed
        // TODO add your handling code here:
        new DodajClana(this, false).setVisible(true);
    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void btnPrikaziClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziClanaActionPerformed
        // TODO add your handling code here:
        int row = tblClanovi.getSelectedRow();
        ModelTabeleClanovi mt = (ModelTabeleClanovi) tblClanovi.getModel();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali ni jednog clana iz tabele!");
            return;
        }else{
            ClanForma cf = new ClanForma(this, false, mt.vratiClana(row));
            cf.setVisible(true);
        }
    }//GEN-LAST:event_btnPrikaziClanaActionPerformed

    private void txtPretragaČlanovaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaČlanovaKeyReleased
        // TODO add your handling code here:
        ModelTabeleClanovi mt = (ModelTabeleClanovi) tblClanovi.getModel();
        String parametar = txtPretragaČlanova.getText();
        mt.setParametar(parametar);
        //mt.refreshTable();
        if (mt.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje clanove po zadatoj vrednosti!");
        }
    }//GEN-LAST:event_txtPretragaČlanovaKeyReleased

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed
        try {
            // TODO add your handling code here:
            int row = tblClanovi.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise clana! Niste selektovali clana za brisanje!");
                return;
            }
            int option = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete clana?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.NO_OPTION) {
                return;
            }
            ModelTabeleClanovi mt = (ModelTabeleClanovi) tblClanovi.getModel();
            Clan clan = mt.vratiClana(row);
            ClientController.getInstance().deleteClan(clan);
            mt.refreshTable();
            JOptionPane.showMessageDialog(this, "Clan je obrisan!");
            return;
        }catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void btnDodajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajKnjiguActionPerformed
        // TODO add your handling code here:
        new DodajKnjiguForma(this).setVisible(true);
    }//GEN-LAST:event_btnDodajKnjiguActionPerformed

    private void txtPretragaKnjigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKnjigaKeyReleased
        // TODO add your handling code here:
        ModelTabeleKnjige mt = (ModelTabeleKnjige) tblKnjige.getModel();
        mt.setParametar(txtPretragaKnjiga.getText());
        mt.refreshTable();
        if (mt.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje knjige po zadatoj vrednosti!");
        }
    }//GEN-LAST:event_txtPretragaKnjigaKeyReleased

    private void btnPrikaziKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziKnjiguActionPerformed
        // TODO add your handling code here:
        int row = tblKnjige.getSelectedRow();
        ModelTabeleKnjige mt = (ModelTabeleKnjige) tblKnjige.getModel();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali ni jednu knjigu iz tabele!");
            return;
        }else{
            KnjigaForma kf = new KnjigaForma(this, false, (mt.vratiKnjigu(row)));
            kf.setVisible(true);
        }
    }//GEN-LAST:event_btnPrikaziKnjiguActionPerformed

    private void btnOceniKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOceniKnjiguActionPerformed
        // TODO add your handling code here:
        int row = tblKnjige.getSelectedRow();
        ModelTabeleKnjige mt = (ModelTabeleKnjige) tblKnjige.getModel();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali ni jednu knjigu iz tabele!");
            return;
        }else{
            Knjiga k = mt.vratiKnjigu(row);
            new OcenaKnjige(this, false, k).setVisible(true);
        }
    }//GEN-LAST:event_btnOceniKnjiguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnDodajKnjigu;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnOceniKnjigu;
    private javax.swing.JButton btnPrikaziClana;
    private javax.swing.JButton btnPrikaziKnjigu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTable tblKnjige;
    private javax.swing.JTextField txtPretragaKnjiga;
    private javax.swing.JTextField txtPretragaČlanova;
    // End of variables declaration//GEN-END:variables

    public void refresujClanove() {
        ModelTabeleClanovi model = new ModelTabeleClanovi();
        Thread thread = new Thread(model);
        thread.start();
        tblClanovi.setModel(model);
    }

    public void dodajClana(Clan clan) {
        ModelTabeleClanovi mt = (ModelTabeleClanovi) tblClanovi.getModel();
        mt.dodajClana(clan);
    }

    public void refresujKnjige() {
        ModelTabeleKnjige model = new ModelTabeleKnjige();
        Thread thread = new Thread(model);
        thread.start();
        tblKnjige.setModel(model);
    }
}
