/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.knjiga;

import controller.ClientController;
import domain.Autor;
import domain.AutorKnjige;
import domain.Knjiga;
import domain.OcenaKnjige;
import domain.Zanr;
import domain.ZanrKnjige;
import forme.MainForm;
import forme.autor.DodajAutora;
import forme.zanr.DodajZanr;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli.ModelTabeleAutori;
import modeli.ModelTabeleIzabraniAutori;
import modeli.ModelTabeleIzabraniZanrovi;
import modeli.ModelTabeleKnjige;

/**
 *
 * @author Korisnik
 */
public class DodajKnjiguForma extends javax.swing.JFrame {
    ModelTabeleIzabraniAutori modelAutori;
    ModelTabeleIzabraniZanrovi modelZanrovi;
    MainForm main;

    /**
     * Creates new form DodajKnjiguForma
     */
    public DodajKnjiguForma(MainForm main) {
        initComponents();
        setLocationRelativeTo(null);
        this.main = main;
        modelAutori = new ModelTabeleIzabraniAutori();
        tblAutori.setModel(modelAutori);
        modelZanrovi = new ModelTabeleIzabraniZanrovi();
        tblZanrovi.setModel(modelZanrovi);
        setTitle("Dodaj knjigu");
    }

    public MainForm getMain() {
        return main;
    }

    public void setModelAutori(Autor autor) {
        ModelTabeleIzabraniAutori mt = (ModelTabeleIzabraniAutori) tblAutori.getModel();
        mt.dodajAutora(autor);
    }

    public void setModelZanrovi(Zanr zanr) {
        ModelTabeleIzabraniZanrovi mt = (ModelTabeleIzabraniZanrovi) tblZanrovi.getModel();
        mt.dodajZanr(zanr);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUkloniAutora = new javax.swing.JButton();
        btnDodajAutora = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZanrovi = new javax.swing.JTable();
        btnIzadji = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutori = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDodajZanr = new javax.swing.JButton();
        btnUkloniZanr = new javax.swing.JButton();
        btnKreirajKnjigu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnUkloniAutora.setText("Ukloni autora");
        btnUkloniAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniAutoraActionPerformed(evt);
            }
        });

        btnDodajAutora.setText("Dodaj autora");
        btnDodajAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAutoraActionPerformed(evt);
            }
        });

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Izabrani autori:");

        tblZanrovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZanrovi);

        btnIzadji.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Izabrani zanrovi:");

        tblAutori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAutori);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("PODACI O KNJIZI:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Naziv knjige:");

        btnDodajZanr.setText("Dodaj zanr");
        btnDodajZanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajZanrActionPerformed(evt);
            }
        });

        btnUkloniZanr.setText("Ukloni zanr");
        btnUkloniZanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniZanrActionPerformed(evt);
            }
        });

        btnKreirajKnjigu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKreirajKnjigu.setText("Kreiraj knjigu");
        btnKreirajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajKnjiguActionPerformed(evt);
            }
        });

        jLabel2.setText("Napomena: Na prvo mesto u tabeli stavite osnovni zanr!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDodajZanr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDodajAutora, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUkloniAutora, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(btnUkloniZanr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addComponent(btnKreirajKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(159, 159, 159)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajAutora)
                    .addComponent(btnUkloniAutora))
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodajZanr)
                            .addComponent(btnUkloniZanr))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKreirajKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel6))
                        .addComponent(btnIzadji))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAutoraActionPerformed
        // TODO add your handling code here:
        new DodajAutora(this, false).setVisible(true);
    }//GEN-LAST:event_btnDodajAutoraActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnUkloniAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniAutoraActionPerformed
        // TODO add your handling code here:
        int row = tblAutori.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali autora za uklanjanje!");
            return;
        }else{
            ModelTabeleIzabraniAutori mt = (ModelTabeleIzabraniAutori) tblAutori.getModel();
            mt.obrisiAutora(row);
        }
    }//GEN-LAST:event_btnUkloniAutoraActionPerformed

    private void btnDodajZanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajZanrActionPerformed
        // TODO add your handling code here:
        new DodajZanr(this, false).setVisible(true);
    }//GEN-LAST:event_btnDodajZanrActionPerformed

    private void btnUkloniZanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniZanrActionPerformed
        // TODO add your handling code here:
        int row = tblZanrovi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali ni jedan zanr za brisanje!");
            return;
        }
        ModelTabeleIzabraniZanrovi mt = (ModelTabeleIzabraniZanrovi) tblZanrovi.getModel();
        mt.obrisiZanr(row);
    }//GEN-LAST:event_btnUkloniZanrActionPerformed

    private void btnKreirajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajKnjiguActionPerformed
        
        ModelTabeleIzabraniAutori mtia = (ModelTabeleIzabraniAutori) tblAutori.getModel();
        ModelTabeleIzabraniZanrovi mtiz = (ModelTabeleIzabraniZanrovi) tblZanrovi.getModel();
        
        String naziv = txtNaziv.getText();
        ArrayList<Autor> autori = mtia.getLista();
        ArrayList<Zanr> zanrovi = mtiz.getLista();
        
        ArrayList<AutorKnjige> aklista = new ArrayList<>();
        ArrayList<ZanrKnjige> zklista = new ArrayList<>();
        
        boolean imaViseAutora = false;
        if (autori.size() > 1) {
            imaViseAutora = true;
        }
        
        for (Autor autor : autori) {
            AutorKnjige ak = new AutorKnjige(imaViseAutora, null, autor);
            aklista.add(ak);
        }
        
        for (Zanr zanr : zanrovi) {
            boolean osnovni = false;
            if (zanrovi.get(0).getZanrID() == zanr.getZanrID()) {
                osnovni = true;
            }
            
            ZanrKnjige zk = new ZanrKnjige(osnovni, zanr, null);
            zklista.add(zk);
        }
        
        Knjiga knjiga = new Knjiga(-1, naziv, 0, aklista, zklista, new ArrayList<OcenaKnjige>());
        
        try {
            ClientController.getInstance().addKnjiga(knjiga);
            MainForm main = getMain();
            main.refresujKnjige();
            JOptionPane.showMessageDialog(this, "Uspesno dodata knjiga!");
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(DodajKnjiguForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKreirajKnjiguActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAutora;
    private javax.swing.JButton btnDodajZanr;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnKreirajKnjigu;
    private javax.swing.JButton btnUkloniAutora;
    private javax.swing.JButton btnUkloniZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAutori;
    private javax.swing.JTable tblZanrovi;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
