/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.knjiga;

import controller.ClientController;
import domain.Knjiga;
import forme.MainForm;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author Korisnik
 */
public class OcenaKnjige extends javax.swing.JDialog {
    Knjiga knjiga;

    /**
     * Creates new form OcenaKnjige
     */
    public OcenaKnjige(java.awt.Frame parent, boolean modal, Knjiga knjiga) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ocena knjige - " + knjiga.getNaziv());
        this.knjiga = knjiga;
        lblNazivKnjige.setText(knjiga.getNaziv());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNazivKnjige = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbOcena = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("KNJIGA:");

        lblNazivKnjige.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNazivKnjige.setText("Naziv");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("VASA OCENA:");

        cmbOcena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnSacuvaj.setText("SACUVAJTE OCENU");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNazivKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNazivKnjige))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnSacuvaj)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        String selected = (String) cmbOcena.getSelectedItem();
        int ocena = Integer.parseInt(selected);
        domain.OcenaKnjige ok = new domain.OcenaKnjige(ocena, Session.getInstance().getUlogovani(), knjiga);
        
        try {
            ArrayList<domain.OcenaKnjige> sveOcene = ClientController.getInstance().getAllOcenaKnjige(ok);
            
            ArrayList<domain.OcenaKnjige> oceneOveKnjige = new ArrayList<>();
            
            for (domain.OcenaKnjige ocenaKnjige : sveOcene) {
            if (ocenaKnjige.getKnjiga().getKnjigaID() == knjiga.getKnjigaID()) {
                    oceneOveKnjige.add(ocenaKnjige);
                    System.out.println("Uspesno dodato u listu ove knjige\n");
                    System.out.println(ocenaKnjige.getIznosOcene());
                }
            }
            
            double zbir = 0;
            if (oceneOveKnjige.size() != 0) {
                zbir = (double) (knjiga.getProsecnaOcena() * oceneOveKnjige.size());
            }
            
            oceneOveKnjige.add(ok);
            zbir += ocena;
            //
            System.out.println("Zbir: " + zbir + " Ocena: " + ocena + " Imenilac: "
                    + oceneOveKnjige.size() + " Nova prosecna ocena knjige: " + zbir/(oceneOveKnjige.size()) + "\n");
            
            knjiga.setProsecnaOcena(zbir/(oceneOveKnjige.size()));
            knjiga.setOceneBibliotekara(oceneOveKnjige);
            
            ClientController.getInstance().updateKnjiga(knjiga);
            
            MainForm mf = (MainForm) getParent();
            mf.refresujKnjige();
            
            if (true) {
                JOptionPane.showMessageDialog(this, "Uneli ste ocenu " + ocena + " za knjigu " + knjiga.getNaziv() + "!");
                this.dispose();
            }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(OcenaKnjige.class.getName()).log(Level.SEVERE, null, ex);
                this.dispose();
            }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cmbOcena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNazivKnjige;
    // End of variables declaration//GEN-END:variables
}
