/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.autor;
import domain.Autor;
import domain.Zanr;
/**
 *
 * @author Korisnik
 */
public class AutorForma extends javax.swing.JDialog {
    Autor autor;

    /**
     * Creates new form ZanrForma
     */
    public AutorForma(java.awt.Frame parent, boolean modal, Autor autor) {
        super(parent, modal);
        initComponents();
        this.autor = autor;
        lblAutorID.setText("AutorID: " + autor.getAutorID());
        lblIme.setText("Ime autora: " + autor.getIme());
        lblPrezime.setText("Prezime autora: " + autor.getPrezime());
        setLocationRelativeTo(null);
        setTitle("Autor - " + autor.getIme() + " " + autor.getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAutorID = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAutorID.setText("AutorID:");

        lblIme.setText("Ime autora:");

        lblPrezime.setText("Prezime autora:");

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutorID)
                            .addComponent(lblIme)
                            .addComponent(lblPrezime)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIzadji)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnIzadji)
                .addGap(18, 18, 18)
                .addComponent(lblAutorID)
                .addGap(48, 48, 48)
                .addComponent(lblIme)
                .addGap(48, 48, 48)
                .addComponent(lblPrezime)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JLabel lblAutorID;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    // End of variables declaration//GEN-END:variables
}
